### ISSUE TITLE
How to run instructions

### ISSUE THREAD

**Issue by sdogruyol** [jwoertink/fez#5]
It's kinda hard to understand 'How to run?' from the README.md.

How about adding a section for that?

**Comment by jwoertink** [comment]
Yeah, I think I can do better with documenting the different options and stuff. Thanks!

**Comment by jwoertink** [comment]
@sdogruyol I've updated the README. https://github.com/jwoertink/fez#usage Let me know if this makes more sense.

**Comment by sdogruyol** [comment]
It's better, thanks a lot 👍 I'm still missing how to start developing with fez though?

Do we use make, guard, just crystal? Could you please document it also

**Comment by jwoertink** [comment]
Oh! I see what you mean. Fez actually generates an app with a README. That generated README is what has the docs on how to start developing. 

I'll add some of that in to the main fez README to make it clear though. Thanks for the help!

~Jeremy

**Comment by jwoertink** [comment]
@sdogruyol Ok, I've added some more docs here https://github.com/jwoertink/fez#working-with-a-fez-generated-app. Funny thing is, while writing those docs, I realized a few issues with the generated app.

I'll close this issue out for now, but if you run in to issues with the generated app, please open up some more issues. I want this thing to be super smooth!. Thanks 👍 😄
